name: Publish Python Package to TestPyPI

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'alain-sv/supervaizer' # Only run on private repo (test PyPI)

    permissions:
      contents: read
      id-token: write # required for trusted publishing if using PyPI's OIDC

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.13"

      - name: Install Hatch
        run: pip install hatch

      - name: Build package
        run: hatch build

      - name: Publish to TestPyPI on develop
        if: github.ref == 'refs/heads/develop'
        run: hatch publish --no-prompt
        env:
          HATCH_INDEX_REPO: https://test.pypi.org/legacy/
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TEST_API_TOKEN }}
