name: TruffleHog Full Repository Scan

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: "Scan Type"
        required: true
        default: "full-repo"
        type: choice
        options:
          - full-repo

jobs:
  full-security-scan:
    name: Full Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full git history for complete scanning

      - name: Full Repository Scan
        if: inputs.scan_type == 'full-repo'
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
